### ISSUE TITLE
Differences between reported action and duplex detections mAP%

### ISSUE THREAD

**Issue by rowandempster** [gurkirt/3D-RetinaNet#8]
Regarding the task metrics reported for the val-1 split in the report:
![image](https://user-images.githubusercontent.com/15329294/128047410-9904e9da-17f3-4ced-9506-c20c4b60a034.png)
Could you clarify how it is possible for the duplex-detection mAP% to be greater than the action-detection mAP% ? Based on the duplex-task description given in report section 3.4, it seems that action-detection is a subtask of duplex-detection. Therefore if duplex-detection mAP% is 28, action-detection should be at least that.

**Comment by gurkirt** [comment]
We don't consider all the possible duplexes due to long-tail problems. We trim the duplex and triplet classes, we only consider them if at least one sample is present in all the splits. Hence, there are limited duplex classes, e.g. car-turn-left is considered as duplex and medVeh-turn-left is not, but all the examples of "Turnleft" action class are considered in the action-detection problem. 

I hope that helps.
